### ISSUE TITLE
Cannot open default libao device

### ISSUE THREAD

**Issue by Popolon** [thp/wavbreaker#13]
I tried wavbreaker on Archlinux ([AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=wavbreaker))

And when I launch it from the terminal, open a sample, and then click on play, I have the following message on terminal :
`Cannot open default libao device`

As I have pulseaudio + pipewire layers, I changed in `/etc/libao.onf` :
`default_driver=alsa`
to
`default_driver=pulse`
as recommanded [with pulseaudio on archlinux](https://wiki.archlinux.org/index.php/PulseAudio#libao)

This doesn't resolve the issue.

After libao.conf manpage, the following drviers are supported :
`pulse,  oss, esd, arts, alsa, nas, irix, sun, roar and sndio.`

**Comment by thp** [comment]
Did you try for a test to disable Pipewire and running just Pulse to see if this resolves the issue?

**Comment by Popolon** [comment]
Sorry for the long time for the answer. I disabled pipewire :
systemctl --user stop pipewire.socket
systemctl --user stop pipewire

* I then verified that I have still the sound with an application that uses pulseaudio (ok)
* I started wavbreaker and opened a sample
* I tried to play the sample, same error.

**Comment by thp** [comment]
Were you able to get the issue sorted out? Does any other libao-using application have the same error?

**Comment by Popolon** [comment]
Looks like it works now.
