### ISSUE TITLE
irregularly spaced break points, and batch processing

### ISSUE THREAD

**Issue by bruce-simonson** [thp/wavbreaker#16]
I am finding this tool very helpful, thanks.

Is there a way to specify irregularly spaced break points to apply to multiple WAV files?

Here's description of my project, and current need (request):

I am recording multiple sound sources (16 singers, each with their own microphone), concurrently, using an audio mixer with the ability to save each singer's work in a separate WAV file.  This results in multiple WAV files, one for each singer.  We do multiple takes (of irregular length), leaving the recorder running throughout).

I would like to define break points between each take; e.g., at 0:00, 1:30, 3:15, 6:00, ... minutes (note that the takes may be of different duration).  I find these points by inspecting the first WAV file.  

I would like to save these break points to some kind of a configuration (parameter) file, so that each of the sixteen tracks is split at these same breakpoints.

Even better would be a batch utility or command line version which would take a WAV file, and a CSV file as a parameter (the CSV file would contain the break points), and generate an appropriate set of files corresponding to the individual takes within the WAV file.

This functionality would be very welcome, in my current project, with 12 break points (13 takes, of irregular length) in each of the 16 WAV files.  

I have no idea how to add this functionality to WAVBREAKER:

a) specify a set of irregularly spaced break points, and save these to a file which can be loaded to drive the splitting process, and
b) do a batch version of this, where the same break point file could be applied to multiple WAV files

Any suggestions?  Any smart programmers up to the challenge?

Thanks,
-Bruce

**Comment by thp** [comment]
You can use the "Import track breaks" and "Export track breaks" feature for this, you can find it right in the menu: 

<img width="310" alt="Screenshot 2021-03-09 at 07 23 35" src="https://user-images.githubusercontent.com/135241/110427764-85a55c80-80a8-11eb-8bd5-b4e2c59baa0b.png">

The batch conversion feature isn't implemented.

**Comment by thp** [comment]
I actually had a slightly different use case for the batch processing that motivated the script, but there is now [`contrib/track-break-to-ffmpeg.py`](https://github.com/thp/wavbreaker/blob/master/contrib/track-break-to-ffmpeg.py) in Git that will turn a .txt file from the "Export track breaks" feature into a shell script that uses `ffmpeg` for cutting the file up, which might be right what you need :)

**Comment by thp** [comment]
The master branch now builds an experimental `wavcli` tool that you can use like this:

```
wavcli split filename.wav filename.txt out
```

This would take the audio file `filename.wav` with the track breaks from `filename.txt` (written using "Export track breaks") and save files to the folder `out`.

To create the `filename.txt`, open the audio file in the GUI, create your track breaks wherever you want to place them, then "Export track breaks".
